-- AlterTable
ALTER TABLE "Results" ADD COLUMN     "place" INTEGER NOT NULL DEFAULT 0;

-- AddForeignKey
ALTER TABLE "Results" ADD CONSTRAINT "Results_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
